### PR TITLE
ENG-1276: enable all bk output to get logged, not just command

### PR DESCRIPTION
**Pull request by petemounce**
#### Description
(This is a canary)

#### Tests
How did you test these changes prior to submitting this pull request?
What automated tests are included in this PR?

#### Documentation
How is this documented (for example: release note, upgrade guide, feature page, in-code documentation)?

**Did you remember a changelog entry?**

#### Primary reviewers
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this request. @ mention them.

### CODE REVIEW

**Comment by petemounce** [comment]
@jamiebrynes7 Looks good. Would you like me to run a promote-bake?

**Comment by jamiebrynes7** [comment]
@petemounce Already did https://buildkite.com/improbable/platform-bakery/builds/1109 😉

**Comment by petemounce** [comment]
Ah, wonderful. Have you done the rollout steps within the platform repo, as described in the annotation? If you haven't, please do, then I'll scale up the managed instance group for you to report on.

**Comment by jamiebrynes7** [comment]
Not yet - will update this PR with the new queue

**Pull request merged**
