### PR TITLE
updating to latest unity

### PR DESCRIPTION
**Pull request by jessicafalk**
**Contributions**: We are not currently taking public contributions - see our [contributions](https://docs.improbable.io/unity/alpha/contributing) policy. However, we are accepting issues and we do want your [feedback](../README.md#give-us-feedback).

-------

#### Description
Describe your changes here.

#### Tests
How did you test these changes prior to submitting this pull request?
What automated tests are included in this PR?

#### Documentation
How is this documented (for example: release note, upgrade guide, feature page, in-code documentation)?

#### Primary reviewers
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this request. @ mention them.

### CODE REVIEW

**Comment by samiwh** [comment]
What does this change? If nothing needs to change can we not just make a docs change saying 2018.2.* will work?

**Comment by jessicafalk** [comment]
what changes is that people opening this project will get a warning that this project was not made with the latest version, if we don't update.

**Comment by jessicafalk** [comment]
don't see the reason why we shouldn't upgrade?

**Comment by jessicafalk** [comment]
plus we don't know if 2018.2.15 will work, if it gets released at some point. so it's better to pin to a specific version

**Comment by samiwh** [comment]
Fair enough.

**Pull request merged**
