### PR TITLE
Unity 2019.3 Upgrade

### PR DESCRIPTION
**Pull request by jamiebrynes7**
#### Description

Unity 2019.3 upgrade

- Some things have moved from experimental to non-experimental
- New queue, who dis?
- Unity auto-upgraded some config files

I don't want to roll this into `develop` until we've released `v0.3.3`. That then gives us a full release cycle on 2019.3 to find any oddities/bugs in 2019.3

#### Tests

QA happening on the FPS project since its more representative --> https://buildkite.com/improbable/gdk-for-unity-fps-starter-project-release-qa/builds/87

#### Documentation

- [x] Changelog

### CODE REVIEW

**Comment by zeroZshadow** [comment]
Try opening the project through cli with `-disable-assembly-updater` to see if nothing is automatically updating.

**Comment by jamiebrynes7** [comment]
2019.3 appears to break Android at runtime and iOS at build time on MacOS machines.

**Comment by jamiebrynes7** [comment]
iOS fixed in https://github.com/spatialos/gdk-for-unity/pull/1272/commits/3f5d23ea0cea2ecfe49b6697a178ce5e6055a4e5 🎉

**Comment by jamiebrynes7** [comment]
Closing (leaving the branch up) as Android requires downstream changes

**Pull request closed without merging**
