### PR TITLE
Change line endings to be platform specific.

### PR DESCRIPTION
**Pull request by martinzlocha**
**Contributions**: We are not currently taking public contributions - see our [contributions](CONTRIBUTING.md) policy. However, we are accepting issues and we do want your [feedback](../README.md#give-us-feedback).

-------

#### Description
Unix line endings should be used instead of dos so that there are no warnings on mac.

#### Tests
Run codegen, no dos line endings in codegened files were found.

#### Documentation
N/A

#### Primary reviewers
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this request. @ mention them.

### CODE REVIEW

**Comment by jessicafalk** [comment]
Test this also on a Windows machine. Just ran it and now I'm getting the warnings on windows ;)

**Comment by martinzlocha** [comment]
@jessicafalk The code is now using System.Environment.NewLine, please have a look. I think it throws warnings if you codegen with an open editor but when you reopen it OK and you can now codegen without closing.

**Comment by jamiebrynes7** [comment]
@martinzlocha You'll want to check in any generated code that changed too

**Comment by martinzlocha** [comment]
@jamiebrynes7 Thats not needed in this case because this change doesn't affect the generated code which we have checked in.

**Comment by jamiebrynes7** [comment]
Oh my, somewhere some generated code that should be checked in.. hasn't been :/

**Comment by jessicafalk** [comment]
do we want to add that generated code back in in this PR or a separate one?

**Comment by martinzlocha** [comment]
screenshot_12

I was just looking at the generated code and I realized that if we use System.Environment.NewLine we have those two lines end with CRLF but all others are only LF. Also the issue with using System.Environment.NewLine in committed code is that every time someone commits on different OS it will ask him to commit the code generated files. Even though its not the nicest of solutions I think we should be using "\n" everywhere.

@jessicafalk I will add the codegened files here.

**Comment by martinzlocha** [comment]
Tested on mac and everything seems to work fine.

**Comment by samiwh** [comment]
@jessicafalk @martinzlocha normally I'd argue the generated code should be added back in with a separate PR as this is a codegen change so it would make this review easier. However given this is the one place where the exhaustive generated code will act differently from the other generated code (checking it in changes the line endings) I think it's fine to do it as a driveby.

**Comment by martinzlocha** [comment]
@zeroZshadow Yes I should change the name of the PR. I realized that changing all line endings to unix is not practical and this is a better solution. I will change the pr name.

**Comment by zeroZshadow** [comment]
However because it is now platform specific, the tests will constantly show up as changed as some of us work on unix systems and the others on windows.

**Comment by martinzlocha** [comment]
@zeroZshadow Just tested this on Mac and after codegening there have been no changes picked up by git so I think it should be fine. If something arises though we can have a look again and convert everything to just /n

**Pull request merged**
