### PR TITLE
Docs: Add ToCs

### PR DESCRIPTION
**Pull request by tenevdev**
#### Description
ToCs would help navigating the glossary a lot. They should be useful for the tutorial and getting started, too.

#### Tests
Local preview

Health pickup tutorial looks like this:
image

Glossary looks like this:
image

### CODE REVIEW

**Comment by jamiebrynes7** [comment]
The TOC on the glossary looks a little funky

**Comment by jamiebrynes7** [comment]
image

**Comment by tenevdev** [comment]
I think it will look nicer when we add some structure to it. I discussed having alphabetical and semantic orderings with @ElleEss. For reference check out https://docs.improbable.io/reference/13.3/shared/glossary

**Comment by jamiebrynes7** [comment]
Yeah if we do that sort of thing it'll be much nicer 😄

**Comment by firtina-improbable** [comment]
OK, I'll rebase and get fresh screenshots

**Comment by firtina-improbable** [comment]
Fresh screenshots are now in the PR description

For glossary, happy to join categorization discussions, waiting for responses from @ernopp and @callumlawson

**Comment by ernopp** [comment]
Sorry for the slow response. I think that since the health pick up tutorial is so long it is worth having a ToC for it so people can more easily navigate it and know where they are with it

**Pull request merged**
