### PR TITLE
Experimental/core refactor

### PR DESCRIPTION
**Pull request by samiwh**
#### Description
There may be changes

Moving the new core into develop rather than an experimental branch.

#### Left todo before merging:
- [x] Test on mobile devices
- [x] Enumerate breaking changes into changelog --> #792 
- [x] Add generated code to test project --> #810

### CODE REVIEW

**Comment by jamiebrynes7** [comment]
Verified this works for Android. iOS next..

**Comment by jamiebrynes7** [comment]
IL2CPP build worked for a UnityClient locally.

**Comment by samiwh** [comment]
Fps starter project has been upgraded and is working

**Comment by samiwh** [comment]
Codegen tests added. Everything looks good.

**Pull request merged**
