### PR TITLE
Add more detailed profiling markers 

### PR DESCRIPTION
**Pull request by gkassabli**
**Contributions**: We are not currently taking public contributions - see our [contributions](https://docs.improbable.io/unity/alpha/contributing) policy. However, we are accepting issues and we do want your [feedback](../README.md#give-us-feedback).

-------

#### Description
This PR adds more detailed profiling markers that allow differentiating between component methods when profiling

#### Tests
Generate components with these changes -> Profile the project -> Ensure that different methods are displayed as separate entities

#### Documentation
Is this significant enough to go to change log?

### CODE REVIEW

**Comment by paulbalaji** [comment]
probably need to change the branch name to run it through CI

**Comment by samiwh** [comment]
FYI this will need to be redone in the near future as this is going away. However the performance characteristics will also be changing a lot so we may want to profile in different places anyway.

**Comment by samiwh** [comment]
FYI this will need to be redone in the near future as this is going away. However the performance characteristics will also be changing a lot so we may want to profile in different places anyway.

**Comment by gkassabli** [comment]
Closing this PR to create a new branch

**Pull request closed without merging**
